matlab -r "filtering_out_2_TIP(0)" &
matlab -r "filtering_out_2_TIP(1)" &
matlab -r "filtering_out_2_TIP(2)" &
matlab -r "filtering_out_2_TIP(3)" &
matlab -r "filtering_out_2_TIP(4)" &
matlab -r "filtering_out_2_TIP(5)" &
matlab -r "filtering_out_2_TIP(6)" &
matlab -r "filtering_out_2_TIP(7)" &
matlab -r "filtering_out_2_TIP(8)" &
matlab -r "filtering_out_2_TIP(9)" &
matlab -r "filtering_out_2_TIP(10)" &
matlab -r "filtering_out_2_TIP(11)" &
matlab -r "filtering_out_2_TIP(12)" &
matlab -r "filtering_out_2_TIP(13)" &
matlab -r "filtering_out_2_TIP(14)" &
matlab -r "filtering_out_2_TIP(15)" &
matlab -r "filtering_out_2_TIP(16)" &
