matlab -r "SSearch_on_image_list(0)" &
matlab -r "SSearch_on_image_list(1)" &
matlab -r "SSearch_on_image_list(2)" &
matlab -r "SSearch_on_image_list(3)" &
matlab -r "SSearch_on_image_list(4)" &
matlab -r "SSearch_on_image_list(5)" &
matlab -r "SSearch_on_image_list(6)" &
matlab -r "SSearch_on_image_list(7)" &
matlab -r "SSearch_on_image_list(8)" &
matlab -r "SSearch_on_image_list(9)" &
matlab -r "SSearch_on_image_list(10)" &
matlab -r "SSearch_on_image_list(11)" &
matlab -r "SSearch_on_image_list(12)" &
matlab -r "SSearch_on_image_list(13)" &
matlab -r "SSearch_on_image_list(14)" &
matlab -r "SSearch_on_image_list(15)" &
matlab -r "SSearch_on_image_list(16)" &
